# Generated by Django 3.2 on 2024-06-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrarTareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='decripcionTarea',
            new_name='descripcionTarea',
        ),
    ]
